### PR TITLE
Create operations guide

### PR DESCRIPTION
**Pull request by hobbes-the-tiger**
Moved the operations content under one section (/content/operations-guide).
- Fixed referring URLs
- Added content for /content/operations-guide/_index.md
- Added content for /content/operations-guide/configuration/basic-configuration/_index.md

Content is currently viewable on the staging server.

### CODE REVIEW

**Comment by mwl** [comment]
Please merge with `master`

**Comment by LH-ExcellentAdventure** [comment]
- change "Installating Humio" to "Installing"
- Figure out how to make the left nav match the toc
- Capitalize "parsers"

Everything else looks good!

**Comment by hobbes-the-tiger** [comment]
Closed because of merge conflicts rthat should not exist. Creating new one.

**Comment by hobbes-the-tiger** [comment]
@mwl Can you please help me with this? The checks aren't working. Thanks!

**Comment by mwl** [comment]
I merged the `master` branch into this PR to fix to build issue. Now there's a `ref` issue, which is caused by non-unique `cluster_setup.md` page. I think you need to delete one of them to fix the problem

**Comment by mwl** [comment]
@hobbes-the-tiger I fixed the issue, see https://github.com/humio/docs.humio.com/pull/132/commits/fbc70b9769dba6c0c914e07de76f66d55e315da4 so it's ready to be merged. At least on the technical side of things

**Comment by hobbes-the-tiger** [comment]
Thanks, merging.

**Pull request merged**
